// Common UI Icons using Remix Icons
export {
  RiAddLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  // Navigation
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiBankFill,
  RiBankLine,
  RiBarChartFill,
  // Analytics & Charts
  RiBarChartLine,
  RiBeerFill,
  RiBeerLine,
  RiBellFill,
  RiBellLine,
  RiBikeFill,
  RiBikeLine,
  RiBluetoothFill,
  RiBluetoothLine,
  RiBookFill,
  // Education
  RiBookLine,
  RiBookmarkFill,
  RiBookmarkLine,
  RiBugFill,
  RiBugLine,
  RiBusFill,
  RiBusLine,
  RiCalendarFill,
  RiCalendarLine,
  RiCameraFill,
  RiCameraLine,
  RiCarFill,
  // Transportation
  RiCarLine,
  RiCheckboxBlankCircleLine,
  RiCheckboxBlankLine,
  // Status
  RiCheckboxLine,
  RiCheckLine,
  RiClipboardLine,
  // Actions
  RiCloseLine,
  RiCloudFill,
  RiCloudLine,
  RiCodeFill,
  // Development & Code
  RiCodeLine,
  RiComputerFill,
  // Technology
  RiComputerLine,
  RiCupFill,
  RiCupLine,
  RiDashboardLine,
  RiDatabaseFill,
  RiDatabaseLine,
  RiDeleteBinLine,
  RiDownloadLine,
  RiEarthFill,
  RiEarthLine,
  RiEditLine,
  RiEmotionFill,
  RiEmotionHappyFill,
  RiEmotionHappyLine,
  RiEmotionLine,
  RiEmotionUnhappyFill,
  RiEmotionUnhappyLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFacebookFill,
  // Social & Sharing
  RiFacebookLine,
  RiFileCopyLine,
  RiFileFill,
  // Files & Documents
  RiFileLine,
  RiFileTextFill,
  RiFileTextLine,
  RiFilterLine,
  RiFlashlightFill,
  // Miscellaneous
  RiFlashlightLine,
  RiFolderFill,
  RiFolderLine,
  RiGameFill,
  // Entertainment
  RiGameLine,
  RiGitBranchFill,
  RiGitBranchLine,
  RiGitCommitFill,
  RiGitCommitLine,
  RiGithubFill,
  RiGithubLine,
  RiGitMergeFill,
  RiGitMergeLine,
  RiGitPullRequestFill,
  RiGitPullRequestLine,
  RiGitRepositoryFill,
  RiGitRepositoryLine,
  RiGlobalFill,
  RiGlobalLine,
  RiGraduationCapFill,
  RiGraduationCapLine,
  RiGridLine,
  RiGroupFill,
  RiGroupLine,
  RiHammerFill,
  RiHammerLine,
  RiHeartFill,
  RiHeartLine,
  RiHeartPulseFill,
  // Health & Fitness
  RiHeartPulseLine,
  RiHomeLine,
  RiImageFill,
  RiImageLine,
  RiInstagramFill,
  RiInstagramLine,
  RiKeyFill,
  RiKeyLine,
  RiLineChartFill,
  RiLineChartLine,
  RiLinkedinFill,
  RiLinkedinLine,
  RiLockFill,
  RiLockLine,
  RiMailFill,
  // Communication
  RiMailLine,
  // Layout & Navigation
  RiMenuLine,
  RiMessageFill,
  RiMessageLine,
  RiMoneyDollarCircleFill,
  // Business & Finance
  RiMoneyDollarCircleLine,
  RiMoonFill,
  RiMoonLine,
  RiMovieFill,
  RiMovieLine,
  RiMusicFill,
  RiMusicLine,
  RiNotificationFill,
  RiNotificationLine,
  RiPauseFill,
  RiPauseLine,
  RiPieChartFill,
  RiPieChartLine,
  RiPlaneFill,
  RiPlaneLine,
  RiPlayFill,
  // Media Controls
  RiPlayLine,
  RiRadioButtonLine,
  RiRainyFill,
  RiRainyLine,
  RiRestaurantFill,
  // Food & Drink
  RiRestaurantLine,
  RiRunFill,
  RiRunLine,
  RiSaveLine,
  RiScissorsLine,
  RiSearchLine,
  RiSettingsFill,
  RiSettingsLine,
  RiShareLine,
  RiShieldCheckFill,
  RiShieldCheckLine,
  RiShieldFill,
  // Security & Privacy
  RiShieldLine,
  RiShoppingCartFill,
  RiShoppingCartLine,
  RiSkipBackLine,
  RiSkipForwardLine,
  RiSmartphoneFill,
  RiSmartphoneLine,
  RiStarFill,
  RiStarLine,
  RiStopFill,
  RiStopLine,
  RiStoreFill,
  RiStoreLine,
  RiSunFill,
  // Weather & Nature
  RiSunLine,
  RiTabletFill,
  RiTabletLine,
  // Communication & Social
  RiTeamLine,
  RiTerminalFill,
  RiTerminalLine,
  RiThumbDownFill,
  RiThumbDownLine,
  RiThumbUpFill,
  // Feedback & Ratings
  RiThumbUpLine,
  RiTimeFill,
  // Time & Date
  RiTimeLine,
  RiToolsFill,
  // Tools & Utilities
  RiToolsLine,
  RiTrainFill,
  RiTrainLine,
  RiTwitterFill,
  RiTwitterLine,
  RiUploadLine,
  RiUserAddLine,
  RiUserFill,
  // User & Account
  RiUserLine,
  RiUserSettingsLine,
  RiVideoFill,
  RiVideoLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiWalkFill,
  RiWalkLine,
  RiWifiFill,
  RiWifiLine,
} from "@remixicon/react";
